CREATE_TABLE = ("CREATE TABLE user ("
                "id integer PRIMARY KEY, "
                "email varchar(300), "
                "password varchar(300), "
                "full_name varchar(300), "
                "city integer,"
                "city_ru varchar(300))")
INSERT_VALUES = (
    "INSERT INTO user"
    "('id','email', 'password', 'full_name', 'city', 'city_ru') VALUES "
    "(1,'novlu@mail.com', 'mkdXjIjYM', 'Людмила Новикова', 10, 'Санкт-Петербург'),"
    "(2,'tripper678@yahhaa.com', 'eGGPtRKS5', 'Андрей Васечкин', 11, 'Москва'),"
    "(3,'georgiberidze@mail.com', 'NWRV0Z9ZC', 'Георги Беридзе', 7, 'Тбилиси'),"
    "(4,'oksi.laslas89@mail.com', 'TenhtQOjv', 'Оксана Ласкина', 12, 'Казань'),"
    "(5,'vanyahot888@inmail.com', '5YGRPtYlw', 'Иван Горячий', 13, 'Сочи'),"
    "(6,'yanaturkiy@mail.com', 'rN3HI4elT', 'Яна Ивлева', 4, 'Стамбул'),"
    "(7,'irafromrome@yahhaa.com', 'mWmSmkNsD', 'Ирина Самидзе', 1, 'Рим'),"
    "(8,'pskovstalker@mail.com', 'M572gH5lG', 'Владислав Ванькин', 14, 'Псков'),"
    "(9,'dinadina13@mail.com', 'v2dSbgPYb', 'Дина Левинова', 9, 'Хельсинки'),"
    "(10,'mark.loud@mail.com', 'pz4ZIYu1l', 'Марк Звонкий',15, 'Нижний Новгород')")